package com.app.employeePortal.dynamoDb.entity;

import java.util.Date;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import lombok.Getter;
import lombok.Setter;

@Getter
@Setter
@DynamoDBTable(tableName = "dynamoNote")

public class DynamoNote {

	@DynamoDBHashKey(attributeName = "noteId")
    @DynamoDBAutoGeneratedKey
    private String noteId;

    @DynamoDBAttribute(attributeName = "notes")
    private String notes;

    @DynamoDBAttribute(attributeName = "creation date")
    private Date creationDate;

    @DynamoDBAttribute(attributeName = "liveInd")
    private boolean liveInd;
    
    @DynamoDBAttribute(attributeName = "userId")
    private String userId;
    
    @DynamoDBAttribute(attributeName = "orgId")
    private String orgId;

    @DynamoDBAttribute(attributeName = "callId")
    private String callId;

    @DynamoDBAttribute(attributeName = "eventId")
    private String eventId;
    
    @DynamoDBAttribute(attributeName = "taskId")
    private String taskId;
    
    @DynamoDBAttribute(attributeName = "customerId")
    private String customerId;
    
    @DynamoDBAttribute(attributeName = "leadsId")
    private String leadsId;
    
    @DynamoDBAttribute(attributeName = "opportunityId")
    private String opportunityId;
    
    @DynamoDBAttribute(attributeName = "candidateId")
    private String candidateId;
    
    @DynamoDBAttribute(attributeName = "contactId")
    private String contactId;
    
    @DynamoDBAttribute(attributeName = "investorId")
    private String investorId;
    
    @DynamoDBAttribute(attributeName = "investorOppId")
    private String investorOppId;
    
    @DynamoDBAttribute(attributeName = "investorId")
    private String investorDealId;
    
    @DynamoDBAttribute(attributeName = "requirmentId")
    private String requirmentId;
    
    @DynamoDBAttribute(attributeName = "leaveId")
    private String distributorId;
    
    @DynamoDBAttribute(attributeName = "investorId")
    private String leaveId;
    
    @DynamoDBAttribute(attributeName = "mileageId")
    private String mileageId;
    
    @DynamoDBAttribute(attributeName = "expenseId")
    private String expenseId;
    
    @DynamoDBAttribute(attributeName = "employeeId")
    private String employeeId;

	
}
