package com.app.employeePortal.unboardingWorkflow.service;

import java.util.List;

import com.app.employeePortal.unboardingWorkflow.mapper.SupplierUnboardingStagesRequestMapper;
import com.app.employeePortal.unboardingWorkflow.mapper.SupplierUnboardingStagesResponseMapper;
import com.app.employeePortal.unboardingWorkflow.mapper.SupplierUnboardingWfReqMapper;
import com.app.employeePortal.unboardingWorkflow.mapper.SupplierUnboardingWfRespMapper;

public interface SupplierUnboardingWorkflowService {

	public SupplierUnboardingWfRespMapper saveSupplierUnboardingWorkflow(SupplierUnboardingWfReqMapper requestMapper);

	public List<SupplierUnboardingWfRespMapper> getSupplierUnboardingWorkflowListByOrgId(String orgId);

	public SupplierUnboardingWfRespMapper updateSupplierUnboardingWorkflowDetails(String unboardingWorkflowDetailsId,
			SupplierUnboardingWfReqMapper requestMapper);

	public void deleteSupplierUnboardingWorkflow(String supplierUnboardingWorkflowDetailsId);

	public boolean stageExistsByWeightage(double probability, String supplierUnboardingWorkflowDetailsId);

	public SupplierUnboardingStagesResponseMapper saveSupplierUnboardingStages(SupplierUnboardingStagesRequestMapper requestMapper);

	public List<SupplierUnboardingStagesResponseMapper> getStagesBySupplierUnboardingWorkflowId(
			String supplierUnboardingWorkflowId);

	public SupplierUnboardingStagesResponseMapper updateSupplierUnboardingStages(String supplierUnboardingStagesId,
			SupplierUnboardingStagesRequestMapper requestMapper);

	public void deleteSupplierUnboardingStages(String supplierUnboardingStagesId);

	public List<SupplierUnboardingStagesResponseMapper> getStagesByOrgId(String orgId);

	public SupplierUnboardingStagesResponseMapper updateSupplierUnboardingStagesPubliahInd(
			SupplierUnboardingStagesRequestMapper requestMapper);

	public SupplierUnboardingWfRespMapper updateSupplierUnboardingWorkflowDetailsPublishInd(
			SupplierUnboardingWfReqMapper requestMapper);

	public List<SupplierUnboardingWfRespMapper> getSupplierUnboardingWorkflowListByOrgIdForDropdown(String orgId);

	public List<SupplierUnboardingStagesResponseMapper> getStagesByOrgIdForDropdown(String orgId);


}
