<div style="font-family: Helvetica,Arial,sans-serif;min-width:1000px;overflow:auto;line-height:2">
    <div style="margin:50px auto;width:70%;padding:20px 0">
        <p style="font-size:1.1em"> Dear ${recruitmentOpportunityMapper.candidateName}; </p>
        <p>We regret to inform you that you have not been selected by ${recruitmentOpportunityMapper.customerName} as a ${recruitmentOpportunityMapper.role}.
         For more details contact ${recruitmentOpportunityMapper.recruitOwner}.</p>
        <p style="font-size:0.9em;">Warm Regards<br>${recruitmentOpportunityMapper.recruitOwner}
        <br/>${recruitmentOpportunityMapper.orgName}</p>
        <hr style="border:none;border-top:1px solid #eee"/>
    </div>
</div>