<div style="font-family: Helvetica,Arial,sans-serif;min-width:1000px;overflow:auto;line-height:2">
    <div style="margin:50px auto;width:70%;padding:20px 0">
        <p style="font-size:1.1em">  </p>
        <p>Use the following OTP to complete your validation For Link procedure.</p>
        <h2 style="background: #00466a;margin: 0 ;width: max-content;padding: 0 10px;color: #fff;border-radius: 4px;">
            ${otp?string.computer}</h2>
        <p style="font-size:0.9em;">Thank You<br/>  </p>
        <hr style="border:none;border-top:1px solid #eee"/>
    </div>
</div>