<!DOCTYPE html>
<html>
<head>
<meta charset="ISO-8859-1">
 <meta name='viewport' content='width=device-width, initial-scale=1.0'>
<title>Onboarding Process </title>
</head>
<body>
<div style="margin:50px auto;width:70%;padding:20px 0">
        <p>Congratulation ${candidateDetails.fullName}!!! Welcome to our organization</p>
        <p style="font-size:0.9em;">Thank You<br/>Employee Portal</p>
        <hr style="border:none;border-top:1px solid #eee"/>
    </div>
</body>
</html>