<div style="font-family: Helvetica,Arial,sans-serif;min-width:1000px;overflow:auto;line-height:2">
    <div style="margin:50px auto;width:70%;padding:20px 0">
        <p style="font-size:1.1em"> Dear ${recruitmentOpportunityMapper.candidateName}; </p>
        <p>We are happy to inform that you have progressed onto the next stage for the role with 
         ${recruitmentOpportunityMapper.customerName}.
         For more information kindly connect with the recruitment executive.</p>
        <p style="font-size:0.9em;">Thanks<br>${recruitmentOpportunityMapper.orgName}
        <hr style="border:none;border-top:1px solid #eee"/>
    </div>
</div>